export interface User { id: number; name: string; email: string; phone: string | null; role: 'user' | 'admin' | 'superuser'; active: boolean; last_login: string | null; created_at: string; updated_at: string }
export interface Family { id: number; slug: string; name: string; description: string | null; display_order: number; active: boolean }
export interface Product { id: number; code: string; name: string; family_id: number; description: string | null; technical_specs: any; cost: number; price: number; unit: string; photo_url: string | null; active: boolean }
export interface Customer { id: number; type: 'PF' | 'PJ'; name: string; trade_name: string | null; doc: string | null; email: string | null; phone: string | null; whatsapp: string | null; address_street: string | null; address_number: string | null; address_complement: string | null; address_district: string | null; address_city: string | null; address_state: string | null; address_zip: string | null; segment: string | null; credit_limit: number; notes: string | null; active: boolean }
export interface Quote { id: number; number: string; customer_id: number; user_id: number | null; template_id: number | null; status: 'rascunho' | 'enviado' | 'aprovado' | 'rejeitado' | 'convertido' | 'expirado'; subtotal: number; discount_amount: number; tax_amount: number; total: number; cost_total: number; profit_amount: number; profit_pct: number; profitability: 'rentavel' | 'atencao' | 'nao_rentavel' | 'desconhecido'; payment_terms: string | null; delivery_terms: string | null; valid_until: string | null; notes: string | null; sent_at: string | null; approved_at: string | null; created_at: string; updated_at: string }
export interface QuoteItem { id: number; quote_id: number; product_id: number; qty: number; list_price: number; unit_price: number; discount_pct: number; unit_cost: number; tax_amount: number; line_total: number; line_profit: number; position: number }
export interface Order { id: number; number: string; customer_id: number; user_id: number | null; quote_id: number | null; template_id: number | null; status: 'aberto' | 'aprovado' | 'faturado' | 'cancelado'; subtotal: number; discount_amount: number; tax_amount: number; total: number; payment_terms: string | null; delivery_date: string | null; notes: string | null; created_at: string; updated_at: string }
export interface TaxRule { id: number; name: string; tax_type: 'ICMS' | 'PIS' | 'COFINS' | 'IPI' | 'OUTRO'; rate: number; family_id: number | null; state: string | null; applies_to: 'all' | 'quote' | 'order'; active: boolean }
export interface FamilyRule { id: number; family_id: number; max_discount_pct: number; min_margin_pct: number; default_markup_pct: number; override_role: string; active: boolean }
export interface Template { id: number; scope: 'quote' | 'order'; name: string; body: any; is_default: boolean }
